### ISSUE TITLE
Please remove false Flagship claim (or present evidence for graduation)

### ISSUE THREAD

**Issue by bkimminich** [OWASP/www-project-maryam#6]
Dear @saeeddhqan, the OWASP Project Committee has just recently processed your project graduation request. I noticed that you claim **Flagship** level for OWASP Maryam which has never been assigned to the project _to the best of my knowledge_. Please set the current maturity level to the actual level of **Incubator** in all links, badges and icons used on the website, documentation, GitHub code repo etc. Alternatively please contact <project-committee@owasp.org> with evidence of a past Flagship promotion. Thank you!

## Proof of claimed Flagship  maturity level

<https://github.com/OWASP/www-project-maryam/commit/46795f82314ea94e704293956d05ab51339dc234>

![image](https://user-images.githubusercontent.com/3531020/103237020-b9e0fc00-4946-11eb-9d00-45bed73359c9.png)

![image](https://user-images.githubusercontent.com/3531020/103237047-ca917200-4946-11eb-9b29-12802cca0d23.png)

---

(`CC` @hblankenship)

**Comment by hblankenship** [comment]
I updated the pages to reflect current actual status.

**Comment by bkimminich** [comment]
The code repo page still shows Flagship badge, but it's not in the OWASP org, so Saeed needs to update that himself.

https://github.com/saeeddhqan/Maryam

**Comment by saeeddhqan** [comment]
Done
